---

- name: Download Automation Agent
  get_url: url={{automation_agent_pkg}} dest=/tmp/automation-agent.rpm

- name: Check for existing Automation Agent config file
  stat: path=/etc/mongodb-mms/automation-agent.config
  register: config_file

- name: Back up Automation Agent config file if exists
  command: mv /etc/mongodb-mms/automation-agent.config /etc/mongodb-mms/automation-agent.config.bak
  when: config_file.stat.exists

- name: Install automation agent
  yum: name=/tmp/automation-agent.rpm state=present

- name: Configure Automation Agent config file
  shell: >
    echo -e 'mmsGroupId={{mms_group_id}}' > /etc/mongodb-mms/automation-agent.config &&
    echo -e 'mmsApiKey={{mms_api_key}}' >> /etc/mongodb-mms/automation-agent.config &&
    echo -e 'mmsBaseUrl={{mms_base_url}}' >> /etc/mongodb-mms/automation-agent.config &&
    echo -e 'mmsConfigBackup={{mms_config_backup}}' >> /etc/mongodb-mms/automation-agent.config &&
    echo -e 'logFile={{log_file}}' >> /etc/mongodb-mms/automation-agent.config &&
    echo -e 'logLevel={{log_level}}' >> /etc/mongodb-mms/automation-agent.config &&
    echo -e 'maxLogFiles={{max_log_files}}' >> /etc/mongodb-mms/automation-agent.config &&
    echo -e 'maxLogFileSize={{max_log_file_size}}' >> /etc/mongodb-mms/automation-agent.config

- name: Collect status on /data directory
  stat: path=/data
  register: data_dir  

- name: If /data exists, set ownership to 'mongod'
  command: chown mongod:mongod /data
  when: data_dir.stat.isdir is defined and data_dir.stat.isdir

- name: If /data not exists, create directory and set ownership to 'mongod'
  shell: mkdir /data && chown mongod:mongod /data
  when: data_dir.stat.exists == False

- name: Start Automation Agent, and enable start on boot
  service: name=mongodb-mms-automation-agent state=started enabled=yes

- name: Confirm Automation Agent is running
  command: service mongodb-mms-automation-agent status
  register: agent_status
  failed_when: "'NOT' in agent_status.stdout"
  changed_when: False
